<?php

function cipher_menu() {
    $items = array();
    $items['cipher'] = array(
        'title' => 'Shift Cipher',
        'page callback' => 'drupal_get_form',
        'page arguments' => array('cipher_form'),
        'access callback' => TRUE,
        'type' => MENU_NORMAL_ITEM,
    );
    $items['cipher_success'] = array(
        'title' => 'Success',
        'page callback' => 'cipher_success',
        'access callback' => TRUE,
        'type' => MENU_CALLBACK,
    );
    return $items;
}

function cipher_form() {
    $form['shift_value'] = array(
        '#title' => 'Shift Value',
        '#type' => 'textfield',
        '#description' => t('Please enter the number of places to shift each letter over.'),
        '#required' => TRUE,
    );
    $form['shift_direction'] = array(
        '#title' => 'Shift Direction',
        '#type' => 'textfield',
        '#description' => t('Please enter the direction to shift the letters.'),
        '#required' => TRUE,
    );
    $form['input_phrase'] = array(
        '#title' => 'Phrase',
        '#type' => 'textfield',
        '#description' => t('Which phrase would you like to encrypt?'),
        '#required' => TRUE,
    );

    $form['submit'] = array(
        '#type' => 'submit',
        '#value' => 'Go',
    );
    return $form;
}

function cipher_form_submit($form, &$form_state) {
    //Variables for user input from form
    $shift_value = $form_state['values']['shift_value'];
    $shift_direction = $form_state['values']['shift_direction'];
    $input_phrase = $form_state['values']['input_phrase'];

    //Converts input phrase to array of characters
    $input_phrase_array = str_split($input_phrase);

    $alphabet_array = array('a', 'b', 'c', 'd', 'e', 'f', 'g', 'h', 'i', 'j', 'k', 'l', 'm', 'n', 'o', 'p', 'q', 'r', 's', 't', 'u', 'v', 'w', 'x', 'y', 'z');
    $special_characters = array(' ', '.', ',', '?', '!');

    //Creates array for output keys
    $output_keys = array();

    //Loops through input array of characters and "converts" to array of alphabet index
    foreach ($input_phrase_array as $character) {
        $key = array_search($character, $alphabet_array);
        if ($shift_direction === 'right') {
            $cipher_key = $key + $shift_value;
        }
        else {
            $cipher_key = $key - $shift_value;
        }
        array_push($output_keys, $cipher_key);
    }

    // Creates array for output cipher letters
    $output_cipher_array = array();

    // "Converts" array of output keys to letters by looping through alphabet array
    foreach ($output_keys as $index) {
        array_push($output_cipher_array, $alphabet_array[$index]);
    }

    // Converts output cipher array to string
    $output_cipher_string = implode('', $output_cipher_array);


    $_SESSION['output_keys'] = $output_keys;
    $_SESSION['output_cipher_array'] = $output_cipher_array;
    $_SESSION['output_cipher_string'] = $output_cipher_string;


    $form_state['redirect'] = 'cipher_success';
}

function cipher_success() {
    $output = $_SESSION['output_cipher_string'];
    return $output;
}
