<?php

function cipher_menu() {
    $items = array();
    $items['cipher'] = array(
        'title' => 'Shift Cipher',
        'page callback' => 'drupal_get_form',
        'page arguments' => array('cipher_form'),
        'access callback' => TRUE,
        'type' => MENU_NORMAL_ITEM,
    );
    $items['cipher_success'] = array(
        'title' => 'Success',
        'page callback' => 'cipher_success',
        'access callback' => TRUE,
        'type' => MENU_CALLBACK,
    );
    return $items;
}

function cipher_form() {
    $form['shift_value'] = array(
        '#title' => 'Shift Value',
        '#type' => 'textfield',
        '#description' => t('Please enter the number of places to shift each letter over.'),
        '#required' => TRUE,
    );
    $form['shift_direction'] = array(
        '#title' => 'Shift Direction',
        '#type' => 'textfield',
        '#description' => t('Please enter the direction to shift the letters.'),
        '#element_validate' => array('element_validate_left_or_right'),
        '#required' => TRUE,
    );
    $form['input_phrase'] = array(
        '#title' => 'Phrase',
        '#type' => 'textfield',
        '#description' => t('Which phrase would you like to encrypt?'),
        '#required' => TRUE,
    );

    $form['submit'] = array(
        '#type' => 'submit',
        '#value' => 'Go',
    );
    return $form;
}

function cipher_form_submit($form, &$form_state) {
    //Variables for user input from form
    $shift_value = $form_state['values']['shift_value'];
    $shift_direction = $form_state['values']['shift_direction'];
    $input_phrase = $form_state['values']['input_phrase'];

    //Converts input phrase to array of characters
    $input_phrase_array = str_split($input_phrase);

    $alphabet = array('a', 'b', 'c', 'd', 'e', 'f', 'g', 'h', 'i', 'j', 'k', 'l', 'm', 'n', 'o', 'p', 'q', 'r', 's', 't', 'u', 'v', 'w', 'x', 'y', 'z');

    //Creates array for output keys
    $output_keys = array();
    $sample = array();

    if($shift_direction == 'left'){
        $shift_value = 26 - $shift_value;
    }

    $output_cipher_string = '';

    foreach ($input_phrase_array as $character) {
        if(in_array($character, $alphabet)) {
            $index_of_character = array_search($character, $alphabet);
            $cipher_key = ($index_of_character + $shift_value) % 26;
            $output_cipher_string .= $alphabet[$cipher_key];
        }
        else{
            $output_cipher_string .= $character;
        }
    }

    $_SESSION['output_cipher_string'] = $output_cipher_string;

    $form_state['redirect'] = 'cipher_success';
}

function cipher_success() {
    $output = $_SESSION['output_cipher_string'];
    return $output;
}

//Validates if input is "left" or "right"
function element_validate_left_or_right($element) {
    if($element['#value'] != 'left'){
        if($element['#value'] != 'right') {
            form_error($element, t('Please enter a shift direction of left or right.'));
        }
    }
}
